np.linalg 是 NumPy 库中专门用于线性代数计算的模块。它提供了一系列函数来执行矩阵和向量运算，是科学计算和数据分析中不可或缺的工具。

1. 矩阵和向量运算

    np.dot(a, b) / a @ b：矩阵乘法或向量点积

    np.inner(a, b)：向量内积

    np.outer(a, b)：向量外积

    np.cross(a, b)：向量叉积（仅限3D）

In [1]:
import numpy as np

# 矩阵乘法示例
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 两种矩阵乘法方式
result1 = np.dot(A, B)
result2 = A @ B  # 推荐使用，更直观
print("矩阵乘法结果:\n", result1)

矩阵乘法结果:
 [[19 22]
 [43 50]]


2. 矩阵分解

    np.linalg.cholesky(a)：Cholesky 分解（用于正定矩阵）

    np.linalg.qr(a)：QR 分解

    np.linalg.svd(a)：奇异值分解（SVD）

    np.linalg.eig(a)：特征值分解

In [2]:
# 奇异值分解示例
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, Vt = np.linalg.svd(A)

print("U 矩阵形状:", U.shape)
print("奇异值:", S)
print("Vt 矩阵形状:", Vt.shape)

# 特征值分解示例
A_square = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A_square)
print("特征值:", eigenvalues)
print("特征向量:\n", eigenvectors)

U 矩阵形状: (3, 3)
奇异值: [9.52551809 0.51430058]
Vt 矩阵形状: (2, 2)
特征值: [3. 2.]
特征向量:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


3. 矩阵求逆与线性方程组求解

    np.linalg.inv(a)：矩阵求逆

    np.linalg.pinv(a)：Moore-Penrose 伪逆

    np.linalg.solve(a, b)：求解线性方程组

In [3]:
# 矩阵求逆
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print("A 的逆矩阵:\n", A_inv)

# 验证：A × A⁻¹ ≈ 单位矩阵
print("验证 A × A⁻¹:\n", A @ A_inv)

# 求解线性方程组
# 方程组：1*x1 + 2*x2 = 5
#         3*x1 + 4*x2 = 6
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

x = np.linalg.solve(A, b)
print("方程组的解:", x)
print("验证 Ax = b:", np.allclose(A @ x, b))  # 应该返回 True

A 的逆矩阵:
 [[-2.   1. ]
 [ 1.5 -0.5]]
验证 A × A⁻¹:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
方程组的解: [-4.   4.5]
验证 Ax = b: True


4. 矩阵性质与范数

    np.linalg.det(a)：矩阵行列式

    np.linalg.matrix_rank(a)：矩阵秩

    np.linalg.norm(x, ord=None)：向量或矩阵范数

    np.linalg.cond(a)：矩阵条件数

In [4]:
# 行列式计算
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print("A 的行列式:", det_A)

# 矩阵秩
A_low_rank = np.array([[1, 2], [2, 4]])  # 第二行是第一行的倍数
rank_A = np.linalg.matrix_rank(A_low_rank)
print("矩阵的秩:", rank_A)

# 向量范数
v = np.array([3, 4])
l2_norm = np.linalg.norm(v)        # L2 范数（默认）
l1_norm = np.linalg.norm(v, ord=1) # L1 范数
print("向量的 L2 范数:", l2_norm)
print("向量的 L1 范数:", l1_norm)

A 的行列式: -2.0000000000000004
矩阵的秩: 1
向量的 L2 范数: 5.0
向量的 L1 范数: 7.0


5. 其他重要函数

    np.linalg.lstsq(a, b)：最小二乘解

    np.linalg.matrix_power(a, n)：矩阵幂

    np.linalg.tensorinv(a)：张量求逆

In [5]:
# 最小二乘法示例
# 拟合 y = mx + c
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])

A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
print(f"拟合直线: y = {m:.2f}x + {c:.2f}")

拟合直线: y = 1.00x + -0.95


错误处理

线性代数运算可能会遇到奇异矩阵等问题，需要进行适当的错误处理：

In [6]:
# 处理奇异矩阵的情况
A_singular = np.array([[1, 2], [1, 2]])  # 奇异矩阵（行线性相关）

try:
    A_inv = np.linalg.inv(A_singular)
except np.linalg.LinAlgError as e:
    print("求逆失败:", e)
    # 可以使用伪逆作为替代
    A_pinv = np.linalg.pinv(A_singular)
    print("使用伪逆:\n", A_pinv)

求逆失败: Singular matrix
使用伪逆:
 [[0.1 0.1]
 [0.2 0.2]]


<pre>应用场景总结
函数类别	主要应用	                常用函数
矩阵运算	神经网络、图形变换	        @, dot, norm
矩阵分解	降维、推荐系统	        svd, eig, qr
方程求解	物理模拟、优化问题	        solve, lstsq
矩阵求逆	统计建模、控制系统	        inv, pinv
矩阵性质	稳定性分析、可逆性判断	det, matrix_rank, cond