介绍numpy的一些操作

In [1]:
import numpy as np 
A=np.arange(3,15).reshape(3,4)
print(A)
print("索引")
print(A[2][3])
print(A[2,3])
print(A[1,1:])
print("遍历输出列")
for column in A.T:
    print(column)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
索引
14
14
[ 8  9 10]
遍历输出列
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [2]:
print("遍历输出元素")
print(A.flatten())
for item in A.flat:
    print(item)#item是地址，即迭代器

遍历输出元素
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [3]:
A=np.array([1,1,1])
B=np.array([2,2,2])
print(f"矩阵A:{A},矩阵B:{B},shape:{A.shape},{B.shape}")

矩阵A:[1 1 1],矩阵B:[2 2 2],shape:(3,),(3,)


In [4]:
C=np.vstack((A,B))
D=np.hstack((A,B))
print(f"上下堆叠矩阵C:{C},左右堆叠矩阵D:{D}")
print(f"堆叠之后的shape:{C.shape},{D.shape}")

上下堆叠矩阵C:[[1 1 1]
 [2 2 2]],左右堆叠矩阵D:[1 1 1 2 2 2]
堆叠之后的shape:(2, 3),(6,)


In [5]:
print(f"矩阵A:{A},矩阵B:{B}")
print(f"加入轴之前的shape:{A.shape},{B.shape}")
A=A[np.newaxis,:]#加到第一个维度前面
B=B[np.newaxis,:]#加到第一个维度前面
print(f"矩阵A:{A},矩阵B:{B}")
print(f"加入轴之后的shape:{A.shape},{B.shape}")

矩阵A:[1 1 1],矩阵B:[2 2 2]
加入轴之前的shape:(3,),(3,)
矩阵A:[[1 1 1]],矩阵B:[[2 2 2]]
加入轴之后的shape:(1, 3),(1, 3)


In [6]:
E=np.vstack((A,B))
A=A[:,:,np.newaxis]#保留前两个维度，加到最后一个维度后面
B=B[:,np.newaxis]#加到了第二个维度
print(f"矩阵A:{A},矩阵B:{B}")
print(f"加入轴之后的shape:{A.shape},{B.shape}")
print(f"AB上下堆叠成的矩阵E:{E},shape:{E.shape}")

矩阵A:[[[1]
  [1]
  [1]]],矩阵B:[[[2 2 2]]]
加入轴之后的shape:(1, 3, 1),(1, 1, 3)
AB上下堆叠成的矩阵E:[[1 1 1]
 [2 2 2]],shape:(2, 3)


三种堆叠方式  
要求除连接轴外的其他轴形状相同,维度必须相同，不会增加维度  
vstack只能在第一个维度上进行堆叠   
hstack只能在第二个维度上进行堆叠  
dstack深度堆叠只能在第三个维度上进行堆叠  

In [7]:
F=np.array([
    [5,10,12],
    [5.1,8.2,3]
    ])
print(f"矩阵F:{F},shape:{F.shape}")

矩阵F:[[ 5.  10.  12. ]
 [ 5.1  8.2  3. ]],shape:(2, 3)


In [8]:
#EF形状不一样就不能进行堆叠,如(2,3)和(3,3)
G=np.vstack((E,F))
print(f"EF上下堆叠成的矩阵G:{G},shape:{G.shape}")

EF上下堆叠成的矩阵G:[[ 1.   1.   1. ]
 [ 2.   2.   2. ]
 [ 5.  10.  12. ]
 [ 5.1  8.2  3. ]],shape:(4, 3)


In [9]:
G=G[:,np.newaxis]#加到了第二个维度，等价于G=G[:,np.newaxis]
print(f"加入轴之后的矩阵G:{G},shape:{G.shape}")

加入轴之后的矩阵G:[[[ 1.   1.   1. ]]

 [[ 2.   2.   2. ]]

 [[ 5.  10.  12. ]]

 [[ 5.1  8.2  3. ]]],shape:(4, 1, 3)


In [10]:
G=G[:,np.newaxis,:]
print(f"加入轴之后的矩阵G:{G},shape:{G.shape}")

加入轴之后的矩阵G:[[[[ 1.   1.   1. ]]]


 [[[ 2.   2.   2. ]]]


 [[[ 5.  10.  12. ]]]


 [[[ 5.1  8.2  3. ]]]],shape:(4, 1, 1, 3)


In [11]:
H=np.hstack((E,F))
print(f"EF左右堆叠成的矩阵H:{H},shape:{H.shape}")

EF左右堆叠成的矩阵H:[[ 1.   1.   1.   5.  10.  12. ]
 [ 2.   2.   2.   5.1  8.2  3. ]],shape:(2, 6)


In [12]:
H=H[:,np.newaxis]#加到了第二个维度
print(f"加入轴之后的矩阵H:{H},shape:{H.shape}")

加入轴之后的矩阵H:[[[ 1.   1.   1.   5.  10.  12. ]]

 [[ 2.   2.   2.   5.1  8.2  3. ]]],shape:(2, 1, 6)


In [13]:
H=np.hstack((H,H))
print(f"H,H左右堆叠成的矩阵H:{H},shape:{H.shape}")

H,H左右堆叠成的矩阵H:[[[ 1.   1.   1.   5.  10.  12. ]
  [ 1.   1.   1.   5.  10.  12. ]]

 [[ 2.   2.   2.   5.1  8.2  3. ]
  [ 2.   2.   2.   5.1  8.2  3. ]]],shape:(2, 2, 6)


In [14]:
H=H[:,:,np.newaxis]#加到了第三个维度
print(f"加入轴之后的矩阵H:{H},shape:{H.shape}")

加入轴之后的矩阵H:[[[[ 1.   1.   1.   5.  10.  12. ]]

  [[ 1.   1.   1.   5.  10.  12. ]]]


 [[[ 2.   2.   2.   5.1  8.2  3. ]]

  [[ 2.   2.   2.   5.1  8.2  3. ]]]],shape:(2, 2, 1, 6)


In [15]:
H=np.hstack((H,H))
print(f"H,H左右堆叠成的矩阵H:{H},shape:{H.shape}")

H,H左右堆叠成的矩阵H:[[[[ 1.   1.   1.   5.  10.  12. ]]

  [[ 1.   1.   1.   5.  10.  12. ]]

  [[ 1.   1.   1.   5.  10.  12. ]]

  [[ 1.   1.   1.   5.  10.  12. ]]]


 [[[ 2.   2.   2.   5.1  8.2  3. ]]

  [[ 2.   2.   2.   5.1  8.2  3. ]]

  [[ 2.   2.   2.   5.1  8.2  3. ]]

  [[ 2.   2.   2.   5.1  8.2  3. ]]]],shape:(2, 4, 1, 6)


能够对张量在指定轴上进行堆叠的的方法concatenate

In [16]:
first=np.array([
    [5,10,12],
    [5.1,8.2,3],
    [5.1,8.2,3]
    ])
second=np.array([
    [5,10,12],
    [5.1,8.2,3]
    ])
first=first[np.newaxis,:]
second=second[np.newaxis,:]
print(f"矩阵first:{first},\n矩阵second:{second},\nshape:{first.shape},{second.shape}")

矩阵first:[[[ 5.  10.  12. ]
  [ 5.1  8.2  3. ]
  [ 5.1  8.2  3. ]]],
矩阵second:[[[ 5.  10.  12. ]
  [ 5.1  8.2  3. ]]],
shape:(1, 3, 3),(1, 2, 3)


In [17]:
A_axis=np.concatenate((first,second,first,second),axis=1)
print(f"沿着轴1进行堆叠,得到矩阵A_axis:{A_axis},shape:{A_axis.shape}")

沿着轴1进行堆叠,得到矩阵A_axis:[[[ 5.  10.  12. ]
  [ 5.1  8.2  3. ]
  [ 5.1  8.2  3. ]
  [ 5.  10.  12. ]
  [ 5.1  8.2  3. ]
  [ 5.  10.  12. ]
  [ 5.1  8.2  3. ]
  [ 5.1  8.2  3. ]
  [ 5.  10.  12. ]
  [ 5.1  8.2  3. ]]],shape:(1, 10, 3)


stack操作  
增加一个维度，在新增的轴上进行堆叠，要求输入张量形状完全相同  
numpy.stack(arrays, axis=0, out=None)  
axis参数决定了堆叠的方向，对输出结果的结构有关键影响

In [18]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])
result_axis0 = np.stack((a,b,a,b), axis=1)
print(result_axis0.shape) 
print(result_axis0)

(2, 4, 2)
[[[1 2]
  [5 6]
  [1 2]
  [5 6]]

 [[3 4]
  [7 8]
  [3 4]
  [7 8]]]


<pre>分割操作 
numpy.split(ary, indices_or_sections, axis=0)
ary:要分割的输入数组.
indices_or_sections:
    如果是​​整数​​，表示​​均分成多少份​​（必须能整除）。
    如果是​​列表/数组​​，表示​​沿轴分割的索引位置​​（如 [2, 5]表示在索引 2 和 5 处分割）.
axis:指定分割的轴（默认 axis=0,即沿行分割）。多维数组分割要指定轴​​
同样有vsplit、hsplit、dsplit，分别是沿着0,1,2轴进行分割
array_split不均等分割，多余的依次从第0轴向后均分

一维数组两种分割方式

In [19]:
arr = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
result = np.split(arr, 2)  # 分成2份
print(result)  # [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
result = np.split(arr, [3, 7])  # 在索引3和7处分割
print(result)  # [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


多维数组分割

In [20]:
A=np.arange(12).reshape((3,4))
B,C=np.split(A,2,axis=1)
print(f"分割前:\n{A}\n分割后:\n矩阵一:\n{B}\n矩阵二:\n{C}")

分割前:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
分割后:
矩阵一:
[[0 1]
 [4 5]
 [8 9]]
矩阵二:
[[ 2  3]
 [ 6  7]
 [10 11]]


In [21]:
D,E,F=np.split(A,(2,3),axis=1)
print(f"分割前:\n{A}\n分割后:\n矩阵一:\n{D}\n矩阵二:\n{E}\n矩阵三:\n{F}")

分割前:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
分割后:
矩阵一:
[[0 1]
 [4 5]
 [8 9]]
矩阵二:
[[ 2]
 [ 6]
 [10]]
矩阵三:
[[ 3]
 [ 7]
 [11]]


其他分割方式  
array_split  
hsplit
vsplit

In [22]:
D,E,F=np.array_split(A,3,axis=1)
print(f"分割前:\n{A}\n分割后:\n矩阵一:\n{D}\n矩阵二:\n{E}\n矩阵三:\n{F}")

分割前:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
分割后:
矩阵一:
[[0 1]
 [4 5]
 [8 9]]
矩阵二:
[[ 2]
 [ 6]
 [10]]
矩阵三:
[[ 3]
 [ 7]
 [11]]


In [23]:
D,E,F=np.vsplit(A,3)
print(f"分割前:\n{A}\n分割后:\n矩阵一:\n{D}\n矩阵二:\n{E}\n矩阵三:\n{F}")

分割前:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
分割后:
矩阵一:
[[0 1 2 3]]
矩阵二:
[[4 5 6 7]]
矩阵三:
[[ 8  9 10 11]]


In [24]:
B,C=np.hsplit(A,2)
print(f"分割前:\n{A}\n分割后:\n矩阵一:\n{B}\n矩阵二:\n{C}")

分割前:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
分割后:
矩阵一:
[[0 1]
 [4 5]
 [8 9]]
矩阵二:
[[ 2  3]
 [ 6  7]
 [10 11]]


In [25]:
arr = np.arange(11)
result = np.array_split(arr, 3)  # 分成3份，允许不等长
print(result)  #多余的依次从第0轴向后均分

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]
