<pre>类别	            常用函数	                                主要用途  
均匀分布	            rand(), random_sample(), uniform()	        生成指定范围内均匀分布的随机浮点数  
正态分布	            randn(), normal()	                        生成符合正态（高斯）分布的随机数  
离散随机整数	    randint()	                                生成指定范围内的离散均匀分布随机整数  
随机抽样与排列	    choice(), shuffle(), permutation()	        从给定数组或序列中随机选择、打乱顺序  
其他分布	            poisson()	                                生成符合其他特定概率分布的随机数  
随机种子	            seed(), RandomState()	                控制随机数生成，确保结果可重现  

均匀分布函数示例

In [2]:
import numpy as np

# 设置随机种子以便结果可重现
np.random.seed(42)

print("=== 均匀分布函数示例 ===")

# 1. rand() - 生成[0,1)均匀分布的数组
print("\n1. rand() 示例:")
rand_array = np.random.rand(2, 3)  # 2x3数组
print(f"rand(2,3):\n{rand_array}")

# 2. random_sample() - 功能同rand()
print("\n2. random_sample() 示例:")
random_sample_array = np.random.random_sample((3, 2))  # 3x2数组
print(f"random_sample((3,2)):\n{random_sample_array}")

# 3. uniform() - 指定范围的均匀分布
print("\n3. uniform() 示例:")
uniform_array = np.random.uniform(low=5, high=10, size=6)  # 6个在[5,10)的数
print(f"uniform(5,10,6): {uniform_array}")

=== 均匀分布函数示例 ===

1. rand() 示例:
rand(2,3):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

2. random_sample() 示例:
random_sample((3,2)):
[[0.05808361 0.86617615]
 [0.60111501 0.70807258]
 [0.02058449 0.96990985]]

3. uniform() 示例:
uniform(5,10,6): [9.1622132  6.06169555 5.90912484 5.91702255 6.52121121 7.62378216]


正态分布函数示例

In [3]:
print("\n=== 正态分布函数示例 ===")

# 1. randn() - 标准正态分布
print("\n1. randn() 示例:")
randn_array = np.random.randn(4)  # 4个标准正态分布数
print(f"randn(4): {randn_array}")

# 2维数组示例
randn_2d = np.random.randn(2, 3)
print(f"randn(2,3):\n{randn_2d}")

# 2. normal() - 自定义参数的正态分布
print("\n2. normal() 示例:")
# 均值为50，标准差为10的正态分布
normal_array = np.random.normal(loc=50, scale=10, size=5)
print(f"normal(50,10,5): {normal_array}")


=== 正态分布函数示例 ===

1. randn() 示例:
randn(4): [-1.72491783 -0.56228753 -1.01283112  0.31424733]
randn(2,3):
[[-0.90802408 -1.4123037   1.46564877]
 [-0.2257763   0.0675282  -1.42474819]]

2. normal() 示例:
normal(50,10,5): [44.55617275 51.1092259  38.49006423 53.75698018 43.9936131 ]


离散随机整数示例

In [4]:
print("\n=== 离散随机整数示例 ===")

# randint() 示例
print("1. 基本用法:")
dice_rolls = np.random.randint(1, 7, size=10)  # 模拟10次掷骰子
print(f"randint(1,7,10): {dice_rolls}")

print("\n2. 生成2D数组:")
matrix = np.random.randint(0, 100, size=(3, 4))  # 3x4矩阵，数值在[0,100)
print(f"randint(0,100,(3,4)):\n{matrix}")

print("\n3. 单个参数用法:")
single_param = np.random.randint(10, size=8)  # 8个[0,10)的随机整数
print(f"randint(10, size=8): {single_param}")


=== 离散随机整数示例 ===
1. 基本用法:
randint(1,7,10): [4 4 4 4 5 3 6 1 4 2]

2. 生成2D数组:
randint(0,100,(3,4)):
[[ 3  1  5 53]
 [ 3 53 92 62]
 [17 89 43 33]]

3. 单个参数用法:
randint(10, size=8): [9 3 7 6 8 7 4 1]


随机抽样与排列示例

In [5]:
print("\n=== 随机抽样与排列示例 ===")

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 1. choice() - 随机选择
print("1. choice() 示例:")
# 不放回抽样
sample_no_replace = np.random.choice(data, size=3, replace=False)
print(f"choice(data, 3, replace=False): {sample_no_replace}")

# 带权重的抽样
weights = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]  # 均匀权重
weighted_sample = np.random.choice(data, size=5, p=weights, replace=True)
print(f"带权重抽样: {weighted_sample}")

# 2. shuffle() - 原地打乱
print("\n2. shuffle() 示例:")
arr_to_shuffle = data.copy()
print(f"原始数组: {arr_to_shuffle}")
np.random.shuffle(arr_to_shuffle)
print(f"shuffle后: {arr_to_shuffle}")

# 3. permutation() - 返回打乱后的新数组
print("\n3. permutation() 示例:")
original_arr = np.array([1, 2, 3, 4, 5])
permuted = np.random.permutation(original_arr)
print(f"原数组: {original_arr}")
print(f"permutation后: {permuted}")
print(f"原数组不变: {original_arr}")


=== 随机抽样与排列示例 ===
1. choice() 示例:
choice(data, 3, replace=False): [90 30 70]
带权重抽样: [30 20 10 50 40]

2. shuffle() 示例:
原始数组: [ 10  20  30  40  50  60  70  80  90 100]
shuffle后: [ 20  50  60  40  10  90  30  70 100  80]

3. permutation() 示例:
原数组: [1 2 3 4 5]
permutation后: [4 2 5 3 1]
原数组不变: [1 2 3 4 5]


其他分布函数示例

In [6]:
print("\n=== 其他分布函数示例 ===")

# poisson() - 泊松分布
print("poisson() 示例:")
# 泊松分布，lambda=3
poisson_data = np.random.poisson(lam=3, size=10)
print(f"poisson(lam=3, size=10): {poisson_data}")

# 其他常用分布示例
print("\n其他分布:")
# 二项分布
binomial_data = np.random.binomial(n=10, p=0.5, size=8)
print(f"二项分布 binomial(10,0.5,8): {binomial_data}")

# 指数分布
exponential_data = np.random.exponential(scale=2.0, size=6)
print(f"指数分布 exponential(2.0,6): {exponential_data}")

# Beta分布
samples = np.random.beta(10,20)
print(f"Beta分布 beta(10,20): {samples}")



=== 其他分布函数示例 ===
poisson() 示例:
poisson(lam=3, size=10): [1 3 3 3 5 0 1 4 3 1]

其他分布:
二项分布 binomial(10,0.5,8): [7 6 6 7 6 4 7 5]
指数分布 exponential(2.0,6): [3.29469658 4.5284853  0.76546143 0.23318432 0.51737349 1.11411539]
Beta分布 beta(10,20): 0.4656242652345166


随机种子控制示例

In [7]:
print("\n=== 随机种子控制示例 ===")

# 1. seed() - 设置随机种子
print("1. seed() 示例:")
np.random.seed(123)
first_random = np.random.rand(3)
print(f"种子123后的随机数: {first_random}")

np.random.seed(123)  # 重置相同种子
second_random = np.random.rand(3)
print(f"相同种子后的随机数: {second_random}")
print(f"两次结果相同: {np.array_equal(first_random, second_random)}")

# 2. RandomState() - 创建独立随机数生成器
print("\n2. RandomState() 示例:")
rng1 = np.random.RandomState(42)
rng2 = np.random.RandomState(42)

print(f"rng1 rand: {rng1.rand(3)}")
print(f"rng2 rand: {rng2.rand(3)}")
print(f"两个生成器结果相同: {np.array_equal(rng1.rand(3), rng2.rand(3))}")


=== 随机种子控制示例 ===
1. seed() 示例:
种子123后的随机数: [0.69646919 0.28613933 0.22685145]
相同种子后的随机数: [0.69646919 0.28613933 0.22685145]
两次结果相同: True

2. RandomState() 示例:
rng1 rand: [0.37454012 0.95071431 0.73199394]
rng2 rand: [0.37454012 0.95071431 0.73199394]
两个生成器结果相同: True


In [8]:
print("\n=== 综合应用示例 ===")

# 模拟掷两个骰子1000次
np.random.seed(42)

print("模拟掷两个骰子1000次:")
dice1 = np.random.randint(1, 7, 1000)
dice2 = np.random.randint(1, 7, 1000)
sums = dice1 + dice2

print(f"骰子1前10次: {dice1[:10]}")
print(f"骰子2前10次: {dice2[:10]}")
print(f"和的前10次: {sums[:10]}")
print(f"和为7的次数: {np.sum(sums == 7)}")
print(f"平均和: {np.mean(sums):.2f}")

# 从结果中随机抽样查看
sample_indices = np.random.choice(len(sums), size=5, replace=False)
print(f"\n随机抽样5个结果:")
for i in sample_indices:
    print(f"  第{i+1}次: 骰子1={dice1[i]}, 骰子2={dice2[i]}, 和={sums[i]}")


=== 综合应用示例 ===
模拟掷两个骰子1000次:
骰子1前10次: [4 5 3 5 5 2 3 3 3 5]
骰子2前10次: [6 5 6 6 4 6 3 6 6 6]
和的前10次: [10 10  9 11  9  8  6  9  9 11]
和为7的次数: 174
平均和: 6.96

随机抽样5个结果:
  第243次: 骰子1=1, 骰子2=2, 和=3
  第430次: 骰子1=3, 骰子2=4, 和=7
  第736次: 骰子1=4, 骰子2=3, 和=7
  第943次: 骰子1=2, 骰子2=1, 和=3
  第74次: 骰子1=4, 骰子2=3, 和=7


<pre>torch.distributions.Categorical(probs)

功能： 创建一个分类分布（离散概率分布）

参数：

    probs：一个概率向量，表示每个类别的概率

    例如：probs = [0.1, 0.3, 0.6] 表示有3个动作，概率分别为10%, 30%, 60%

返回一个Categorical对象,该对象可以使用sample方法进行采样

In [9]:
import torch

# 假设有3个动作，概率分别为10%, 30%, 60%
probs = torch.tensor([0.1, 0.3, 0.6])
action_dist = torch.distributions.Categorical(probs)

print(action_dist)
# 输出: Categorical(probs: torch.Size([3]))

Categorical(probs: torch.Size([3]))


<pre>action_dist.sample()

功能： 从分布中随机采样一个样本

工作原理：

    根据概率分布随机选择一个动作索引

    不是选择概率最大的动作，而是按概率随机选择

In [10]:
# 多次采样观察结果
for i in range(10):
    action = action_dist.sample()
    print(f"采样 {i+1}: 动作 {action.item()}")

采样 1: 动作 1
采样 2: 动作 2
采样 3: 动作 2
采样 4: 动作 2
采样 5: 动作 1
采样 6: 动作 1
采样 7: 动作 2
采样 8: 动作 2
采样 9: 动作 2
采样 10: 动作 1


In [ ]:
np.random.permutation(np.arange(10))
# 随机打乱

array([6, 5, 3, 0, 7, 2, 8, 1, 9, 4])