介绍一些维度变换，线代矩阵运算的知识

In [1]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
x = torch.arange(4, dtype=torch.float32)
A, B,x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

降维  
计算其元素的和sum  
mean或average  

In [5]:
x.shape,A.shape,x.sum(), A.sum()#降为标量

(torch.Size([4]), torch.Size([5, 4]), tensor(6.), tensor(190.))

指定张量沿哪一个轴来通过求和降低一个维度，即指定的维度会被压成一维消失掉

In [7]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape
#轴0表示行，现在只有一行了，变成了行向量（1,4）

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [8]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape
#轴1表示列，现在只有一列了，变成了列向量（5,1）

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

非降维求和  
广播机制要求维度相同，标量除外  
keepdims保持维度

In [13]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A,sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [14]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

线性代数矩阵运算  
向量点积  

In [15]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [16]:
torch.sum(x * y)

tensor(6.)

矩阵与向量相乘  
把矩阵看作一个列向量，列向量的每一行都是行向量  
行向量与被乘的向量作点积  
要求矩阵列数与向量size(也是行向量)相同

In [18]:
A.shape, x.shape, torch.mv(A, x),torch.mv(A, x).shape

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 torch.Size([5]))

矩阵与矩阵的乘法  
要求前面的列等于后面的行  
可以把A看作列向量$\begin{bmatrix} a1\\a2\\...\\am\end{bmatrix}$，B看作行向量$\begin{bmatrix} b1&b2&...&bn\end{bmatrix}$  
$C={\left\{a_i \cdot b_j \right\}}_{m \times n}$  

In [21]:
B = torch.ones(4, 3)
C=torch.mm(A, B)
print(C)
print(A.shape,B.shape,C.shape)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])
torch.Size([5, 4]) torch.Size([4, 3]) torch.Size([5, 3])


向量范数计算  
距离，二范数  
L1范数，绝对值再求和  
还有P范数，(sum(abs(xi)^p))^(1/p) 需要自己搭建

In [22]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [23]:
torch.abs(u).sum()#L1范数

tensor(7.)

矩阵的Frobenius范数  
矩阵元素平方和的平方根

In [ ]:
torch.norm(torch.ones((4, 9)))